version: "3.4"

services:
  frontend:
    image: mikasso/frontend:1.01
    networks:
      - my-network
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
  backend:
    image: mikasso/backend:1.01
    networks:
      - my-network
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000
    ports:
      - 5000:5000

networks:
  my-network:
    external: true
