version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: development
    entrypoint: [ "http-server", "dist" ]
    ports:
      - 80:8080
  backend:
    build:
      context: ./backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
    entrypoint: ["dotnet", "Backend.Service.dll"]
    ports:
      - 5000:5000
